import { createSlice } from "@reduxjs/toolkit";


export const userSlice = createSlice({
  name: "user",
  initialState:{
    user:null,
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    loginuser: (state, action) => {
      state.user = action.payload;
    },
  },
  logoutuser: (state) => {
    state.user=null;
  },
  // Use the PayloadAction type to declare the contents of `action.payload`
  // incrementByAmount: (state, action) => {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});
export const selectUser = (state)=> state.user.user;
export const { loginuser, logoutuser } = userSlice.actions;

export default userSlice.reducer;
